-- MySQL Script generated by MySQL Workbench
-- 04/13/17 17:12:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema invasivespecies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invasivespecies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invasivespecies` DEFAULT CHARACTER SET utf8 ;
USE `invasivespecies` ;

-- -----------------------------------------------------
-- Table `invasivespecies`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invasivespecies`.`species` ;

CREATE TABLE IF NOT EXISTS `invasivespecies`.`species` (
  `speciesId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`speciesId`),
  UNIQUE INDEX `spid_UNIQUE` (`speciesId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invasivespecies`.`panorama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invasivespecies`.`panorama` ;

CREATE TABLE IF NOT EXISTS `invasivespecies`.`panorama` (
  `panoramaId` VARCHAR(64) NOT NULL,
  `lat` DOUBLE NULL,
  `lng` DOUBLE NULL,
  `image` VARCHAR(64) NULL,
  `description` VARCHAR(256) NULL,
  `country` VARCHAR(64) NULL,
  `region` VARCHAR(256) NULL,
  `gsvImageDate` DATE NULL,
  `imap_species_speciesId` INT NOT NULL,
  `noInvasives` TINYINT(1) NULL,
  PRIMARY KEY (`panoramaId`),
  INDEX `fk_panorama_species1_idx` (`imap_species_speciesId` ASC),
  CONSTRAINT `fk_panorama_species1`
    FOREIGN KEY (`imap_species_speciesId`)
    REFERENCES `invasivespecies`.`species` (`speciesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invasivespecies`.`bounding_box`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invasivespecies`.`bounding_box` ;

CREATE TABLE IF NOT EXISTS `invasivespecies`.`bounding_box` (
  `topleftX` INT NULL,
  `topleftY` INT NULL,
  `bottomrightX` INT NULL,
  `bottomrightY` INT NULL,
  `species_speciesId` INT NOT NULL,
  `panorama_panoramaId` VARCHAR(64) NOT NULL,
  INDEX `fk_bounding_box_species_idx` (`species_speciesId` ASC),
  INDEX `fk_bounding_box_panorama1_idx` (`panorama_panoramaId` ASC),
  CONSTRAINT `fk_bounding_box_species`
    FOREIGN KEY (`species_speciesId`)
    REFERENCES `invasivespecies`.`species` (`speciesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bounding_box_panorama1`
    FOREIGN KEY (`panorama_panoramaId`)
    REFERENCES `invasivespecies`.`panorama` (`panoramaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- insert some data to species table

insert into species ( description ) values ('Common Reed (Phragmite)');

insert into species ( description ) values ('Japanese Knotweed');

insert into species ( description ) values ('Wild Parsnip');

insert into species ( description ) values ('Purple Loosestrife');